#!/usr/bin/env bash
# Installs nginx web server
sudo apt-get update
sudo apt install -y nginx
# check if nginx is active, restart if not
if ! sudo systemctl is-active --quiet nginx
then
        if ! sudo service nginx restart
	then
		echo "Unable to start nginx"
		exit 1
	fi
fi
# enable 'Nginx HTTP' through ufw if it is active
if sudo ufw status | grep -q "Status: active"
then
	sudo ufw allow 'Nginx HTTP'
fi
echo "Hello World!" | sudo tee /var/www/html/index.html
#check for any errors with nginx config files
if sudo nginx -t
then
	# reload nginx
	sudo nginx -s reload
else
	echo "Error with nginx config files"
fi
