#!/usr/bin/env bash
# Includes a redirection in site configuration
rep_str=$(cat <<EOL
	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch\?v=QH2-TGUlwu4;
   	}
EOL
)
echo "$rep_str" > temp_file
awk '/\tserver_name _;/ && !found {system("cat temp_file"); found=1; next} 1' /etc/nginx/sites-available/default > output_file
sudo mv output_file /etc/nginx/sites-available/default
#check for any errors with nginx config files
if sudo nginx -t
then
	# reload nginx
	sudo nginx -s reload
else
	echo "Error with nginx config files"
fi
