#!/usr/bin/env bash
# Installs nginx web server and include a redirection in site configuration
sudo apt-get update
sudo apt install -y nginx
# check if nginx is active, restart if not
if ! sudo systemctl is-active --quiet nginx
then
        if ! sudo service nginx restart
	then
		echo "Unable to start nginx"
		exit 1
	fi
fi
# enable 'Nginx HTTP' through ufw if it is active
if sudo ufw status | grep -q "Status: active"
then
	sudo ufw allow 'Nginx HTTP'
fi
# Create index file, write to it
#echo "Hello World!" | sudo tee /var/www/html/index.html
rep_str=$(cat <<EOL
	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch\?v=QH2-TGUlwu4;
   	}
EOL
)
echo "$rep_str" > temp_file
awk '/\tserver_name _;/ && !found {system("cat temp_file"); found=1; next} 1' /etc/nginx/sites-available/default > output_file
sudo rm temp_file
sudo mv output_file /etc/nginx/sites-available/default
#check for any errors with nginx config files
if sudo nginx -t
then
	# reload nginx
	sudo nginx -s reload
else
	echo "Error with nginx config files"
fi
