#!/usr/bin/env bash
# Installs nginx web server and include a redirection in site configuration
sudo apt-get update
sudo apt install -y nginx
# check if nginx is active, restart if not
if ! sudo systemctl is-active --quiet nginx
then
        if ! sudo service nginx restart
	then
		echo "Unable to start nginx"
		exit 1
	fi
fi
# enable 'Nginx HTTP' through ufw if it is active
if sudo ufw status | grep -q "Status: active"
then
	sudo ufw allow 'Nginx HTTP'
fi
#echo "Hello World!" | sudo tee /var/www/html/index.html
#Edit config file for redirection purposes
#redir_conf=$(cat <<EOL
#	server_name _;

#	location /redirect_me {
#		return 301 https://www.youtube.com/watch\?v=QH2-TGUlwu4;
#   }
#EOL
#)
#escaped_redir_conf=$(printf '%s\n' "$redir_conf" | sed 's/[&/\]/\\&/g')
#sudo sed -i "s/\tserver_name _;/$redir_conf/" /etc/nginx/sites-available/default
#sudo sed -i "s|\tserver_name _;|${escaped_redir_conf}|" /etc/nginx/sites-available/default
rep_str=$(cat <<EOL
	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch\?v=QH2-TGUlwu4;
   	}
EOL
)
echo "$rep_str" > temp_file
#awk '/\tserver_name _;/{system("cat temp_file");next}1' /etc/nginx/sites-available/default > output_file
awk '/\tserver_name _;/ && !found {system("cat temp_file"); found=1; next} 1' /etc/nginx/sites-available/default > output_file
sudo mv output_file /etc/nginx/sites-available/default
#check for any errors with nginx config files
if sudo nginx -t
then
	# reload nginx
	sudo nginx -s reload
else
	echo "Error with nginx config files"
fi
