#!/usr/bin/env bash
# Creates a dump of all my MySQL databases and compresses it to a tar.gz archive
# Password
pass=$1
# Dump all databases to backup file
mysqldump -u root -p"$pass "  --all-databases > backup.sql
archive_name=$(date +%d-%m-%Y)
tar -czf "$archive_name.tar.gz" ./backup.sql
