#!/usr/bin/env bash
# Stores own pid in a file, display a string indefinitely, trap SIGTERM, SIGINT, SIGQUIT signals.
(echo $$ | sudo tee /var/run/myscript.pid) > /dev/null
trap 'echo "I hate the kill command" && sudo rm -f "/var/run/myscript.pid" && pkill -f "bash ./100-process_and_pid_file" -SIGKILL' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm -f "/var/run/myscript.pid" && pkill -f "bash ./100-process_and_pid_file" -SIGKILL' SIGQUIT
while true
do
	echo "To infinity and beyond"
done
