#!/usr/bin/env bash
# Creates a file containing this script's pid.
# Displays a string indefinitely.
# When it receives the SIGTERM signal, it displays a string, deletes the file
# containing the pid and terminates itself.
# When it receives the SIGINT signal, it only displays a string message.
# When it receives the SIGQUIT signal, it deletes the file containing the pid
# and terminates itself.
function SIGTERM_handler(){
	echo "I hate the kill command"
	sudo rm -f "/var/run/myscript.pid"
	exit 15
}
function SIGQUIT_handler(){
	sudo rm -f "/var/run/myscript.pid"
	exit 3
}

if echo "$$" | sudo tee /var/run/myscript.pid > /dev/null
then
	while true
	do
		trap 'echo "Y U no love me?!"' SIGINT
		trap 'SIGTERM_handler' SIGTERM
		trap 'SIGQUIT_handler' SIGQUIT
		echo "To infinity and beyond"
	done
fi
