#!/usr/bin/env bash
# Fizz buzz implementation.
count=1
while [ "$count" -lt 101 ]
do
	mod3=$((count%3))
	mod5=$((count%5))
	if [ "$mod3" -eq 0 ] && [ "$mod5" -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ "$mod3" -eq 0 ] && [ "$mod5" -ne 0 ]
	then
		echo "Fizz"
	elif [ "$mod5" -eq 0 ] && [ "$mod3" -ne 0 ]
	then
		echo "Buzz"
	elif [ "$mod5" -ne 0 ] && [ "$mod3" -ne 0 ]
	then
		echo "$count"
	fi
	((count++))
done
