#!/usr/bin/env bash
# Fizz buzz implementation.
# Displays numbers from 0 to 100.
# Displays FizzBuzz when a number is a multiple of both 3 and 5.
# Displays Fizz if a number when a multiple of 3.
# Displays Buzz when the number is a multiple of 5.
count=0
while [ "$count" -lt 101 ]
do
	mod3=$((count%3))
	mod5=$((count%5))
	if [ "$mod3" -eq 0 ] && [ "$mod5" -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ "$mod3" -eq 0 ] && [ "$mod5" -ne 0 ]
	then
		echo "Fizz"
	elif [ "$mod5" -eq 0 ] && [ "$mod3" -ne 0 ]
	then
		echo "Buzz"
	elif [ "$mod5" -ne 0 ] && [ "$mod3" -ne 0 ]
	then
		echo "$count"
	fi
	((count++))
done
