#!/usr/bin/env bash
# Displays 'Best School' 10 times but for the 9th iteration, displays Best School
# and then Hi on a new line.
count=9
while [ "$count" -ge 0 ]
do
	if [ "$count" -eq 1 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((count--))
done
