#!/usr/bin/env bash
# Displays 'Best School' for all but 3 times out of ten, for which an
# alternative message is displayed.
count=0
while [ "$count" -le 9 ]
do
	if [ "$count" -eq 3 ]
	then
		echo "bad luck"
	elif [ "$count" -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
