#!/usr/bin/env bash
# Displays a string depending on the iteration number for 10 iterations.
counter=0
while [ "$counter" -le 9 ]
do
	if [ "$counter" -eq 3 ]
	then
		echo "bad luck"
	elif [ "$counter" -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter+=1))
done
