#!/usr/bin/env bash
# Displays current directory contents.
# The contents are displayed in a list format with one item per line.
# Only the part of the name after the first dash is displayed.
ls -1 | cut -d '-' -f 1 --complement
