#!/usr/bin/env bash
#Changes what localhost and facebook.com resolve to
if [ -e "/etc/hosts" ]
then
	original_s="127\.0\.0\.1"
	replacement_s="127\.0\.0\.2"
	sudo sed -i -E "s/$original_s/$replacement_s/g" "/etc/hosts"
	echo "8.8.8.8	facebook.com" | sudo tee -a /etc/hosts > /dev/null
fi
